### ISSUE TITLE
ES6 modules?

### ISSUE THREAD

**Issue by christopherdumas** [Gozala/wisp#100]
I like all the lisp dialects, and my favorite was Clojure until I saw Wisp! I am so exited that it compiles to JavaScript! But, that said, can I use ES6 modules with it? I am using `Ember App Kit`, which uses them, and I was considering using wisp, but I was not sure it would work with ES6 modules...

**Comment by chr15m** [comment]
@hauleth @christopherdumas is `6to5` sufficient? Can we close this if so?

**Comment by christopherdumas** [comment]
I think it's sufficient.
