### ISSUE TITLE
Wisp with browserify (and wispify or similar) for browser bundles

### ISSUE THREAD

**Issue by mariusk** [Gozala/wisp#117]
I'm trying to get a build pipeline going using wisp and browserify, and it seems browserify is unable to pick up and auto-include the required dependencies. Has anybody succeeded in building browser bundles with the resulting javascript code (after running through wisp)?

**Comment by tillarnold** [comment]
Did you remember to set [opts.extensions](https://github.com/substack/node-browserify#var-b--browserifyfiles-or-opts) to `['.wisp']` in your browserify config?

**Comment by mariusk** [comment]
Tried adding `--extension=.wisp` to my browserify cmdline at it seems to work much better now. Time to try again, thanks!
