### ISSUE TITLE
FYI: CSP channels based on ES6 generators

### ISSUE THREAD

**Issue by walden-** [Gozala/wisp#119]
https://github.com/ubolonton/js-csp

**Comment by Gozala** [comment]
Not sure what this is about.

**Comment by walden-** [comment]
"This is a very close port of Clojurescript's core.async."

Is this not an interesting project for implementing that functionality in wisp?

**Comment by Gozala** [comment]
@walden- I think we can just add syntax for generators and than it will work out of the box. That being said I'd be more interested in getting wisp into a state where core.async can be used as is.

I'm afraid I don't have time to work on either, but will be happy to mentor if someone will be interested in doing it.
