### ISSUE TITLE
Examples of using wisp in web-pages?

### ISSUE THREAD

**Issue by interstar** [Gozala/wisp#120]
Are there examples for using wisp in a web-page?

Looking for a quick-start that's not about using node or command-line repl. Just including compiler and some wisp code in a single-page app.

**Comment by kpullen** [comment]
Well, there is the [try-wisp](https://github.com/Gozala/try-wisp) repository. I took a quick look at `src/main.wisp`, and it appears to be importing `compile` from `wisp.compiler`. I wasn't able to find a drop-in like Traceur or Babel have, but that might be a place to start.

**Comment by chr15m** [comment]
Hey guys, I'm working on this which might help: https://chr15m.github.io/wisp/

**Comment by chr15m** [comment]
Closing this as the docs now demonstrate this clearly.
