### ISSUE TITLE
Error format for the compiler?

### ISSUE THREAD

**Issue by girvo** [Gozala/wisp#135]
I've been working on a `wisp-loader` for webpack [(see here)](https://github.com/girvo/wisp-loader), which is working pretty well thus far.

One thing I can't seem to get is the actual error string itself from the `error` property on the result of `compiler.compile()`. It seems to be a symbol, but I'm unsure how to pull it from it to display in webpack?

```js
{ [SyntaxError: EOF
line:37
column:0]
  line: 37,
  column: 0,
  uri: '/Users/josh/PersonalProjects/Web/immutable-wisp/src/index.wisp' }
```

That's an example `error` object; how do I access the `[SyntaxError: EOF...]` "string"?

**Comment by robjens** [comment]
SyntaxError is a type. The string itself is `EOF` which means, I presume you know but anyway, `end-of-file`. Besides that, there isn't much more information to display besides the location the best way it can using `line` and `column`. To obtain the value, a mere `(.to-string (:error (compile "(def foo 1 (foo)")))` should be sufficient to display those 3 essential parts: message, line and column together with the error type as:

```
SyntaxError: EOF
line:1
column:0
```

**Comment by robjens** [comment]
Oh. And I guess it might be worth to mention that, in this context, the `try ... catch` semantics won't work for you. The way to ensure that it doesn't get dumped to the standard output seems to be something like the following, which could be of use to you:

```clojure

(let [nay-expr "(def foo 1 (foo)"
      yay-expr "(def foo 1) foo"]

  (if (nil? (:error (compile nay-expr)))
    (print (compile nay-expr))
    (do
      (print (.to-string (:error (compile nay-expr))))
      (print "Expression: " nay-expr)))

  (if (nil? (:error (compile yay-expr)))
    (print (compile yay-expr))
    (do
      (print (.to-string (:error (compile yay-expr))))
      (print "Expression: " yay-expr))))
```

**Comment by girvo** [comment]
Awesome, I'll have a play with `transpile` and see if I can get nicer error reporting in my `webpack` loader :)
