### ISSUE TITLE
Wisp is still important

### ISSUE THREAD

**Issue by zot** [Gozala/wisp#148]
Hi there,

I started looking at Wisp a few days ago and I just made a [pull request](https://github.com/Gozala/wisp/pull/147) so that UMD projects using things like requirejs can easily access Wisp and all of its packages.

Wisp seems very lean, dynamic, and well suited to in-browser development, whereas ClojureScript seems to have a very "offline compilation" model and it's also quite bloated compared to Wisp.  I'm looking at adding Wisp to my [Leisure/Lounge](https://github.com/zot/Leisure) environment and using Wisp to build a MUD.  I REALLY like Wisp's lean codebase and I hope we're able to use it.  WIsp seems like a really good tool and it **still seems very important and relevant** to me!

**Comment by chr15m** [comment]
@zot I agree! Let's talk about getting your UMD pull request merged.
