### ISSUE TITLE
Publish to npm as a new version?

### ISSUE THREAD

**Issue by riatzukiza** [Gozala/wisp#157]
I have seen that work has been done on the git recently, but the module on npm is 4 years old.

**Comment by Gozala** [comment]
@chr15m Had being maintaining this project but as I just realized he has no npm publish access. @chr15m Please let me know what's your npm handle and I'd be happy to add you to the npm list so you'll be able to publish

**Comment by chr15m** [comment]
@Gozala I've just created "chr15m" on npm. Will update the package as soon as you give me access. Thank you very much!

**Comment by Gozala** [comment]
Done!

**Comment by chr15m** [comment]
@riatzukiza 

```
$ npm install wisp
...
+ wisp@0.11.1
```

https://www.npmjs.com/package/wisp

\o/
