### ISSUE TITLE
Analyzer unit tests are currently ignored.

### ISSUE THREAD

**Issue by hughfenghen** [Gozala/wisp#166]
Hi, i want try add new feature syntax to the wisp, but I found that the unit test of the analyzer module is ignored.  https://github.com/Gozala/wisp/blob/master/test/test.wisp#L10

Is there any reason?

**Comment by chr15m** [comment]
I think I turned them off when I implemented CI. There was some bug preventing those from passing which was beyond my understanding, but I thought that having most of the codebase tested was better than not turning on tests at all.

Would be good to get this fixed if you or somebody else has the expertise. CC: @LeXofLeviafan @rcarmo

**Comment by LeXofLeviafan** [comment]
@chr15m I'll probably check it out later
@hughfenghen What kind of syntax are you thinking of implementing, BTW? I think Wisp has more or less everything that Clojure supports, syntax-wise; and most other things can be covered by either macros or reader-macros (that's how you normally extend a Lisp ;-) ).

**Comment by hughfenghen** [comment]
@LeXofLeviafan Thanks.

I am a js developer and don't have an in-depth understanding of wisp or coljure.  
I want try [Implement destructuring] (https://github.com/Gozala/wisp/issues/4) to learn related knowledge.

**Comment by chr15m** [comment]
@LeXofLeviafan I personally value stable software quite highly and would tend towards being conservative about merging new features that stray too far from the core of what Wisp does.

@hughfenghen destructuring would be amazing.

**Comment by LeXofLeviafan** [comment]
[destructuring is implemented here](https://github.com/LeXofLeviafan/wisp/commit/3f9eef751ec8f0d511eebaaea2f4dfa8673c9c19)

**Comment by chr15m** [comment]
Wow nice work implementing destructuring! :star2: :100:
