### ISSUE TITLE
How to compile to es2015 or esNext

### ISSUE THREAD

**Issue by rockiger** [Gozala/wisp#173]
I would like to compile wisp code to es2015 or newer. Unfortunately, I don't know where to start.

I understand that the JS code is generated by `escodegen`. But I don't see any configuration options for it.

Could somebody give me a hint on where to start?

**Comment by Gozala** [comment]
Here you can see that call to `generate*` function, which is escodgen `generate` it is given an JS AST along with bunch of options

https://github.com/wisp-lang/wisp/blob/f90410d8341bec417fc64f27bf8d6f670f9907b1/src/backend/escodegen/generator.wisp#L29-L36

But to output modern ES code you’ll probably need to generate modern JS AST. Currently implementation takes expanded wisp forms and uses this write function to produce corresponding JS AST

https://github.com/wisp-lang/wisp/blob/f90410d8341bec417fc64f27bf8d6f670f9907b1/src/backend/escodegen/writer.wisp#L825-L833

**Comment by chr15m** [comment]
@rockiger if you want to transpile wisp to js on the command line you can do something like this:

`npx wisp -c < test.wisp > test.js`

**Comment by rockiger** [comment]
@Gozala Thank you. That sounds like a lot of fun to dig into.

@chr15m I know. I just want different the output to be modern JS. This is just for fun right now. I am playing with the idea of using wisp in a create-react-app project.

**Comment by rockiger** [comment]
I will close that issue. It seems to me that creating esNext code would need a lot of rewriting.
