### ISSUE TITLE
Document `(call …)`and how you can use it to work around name clashes

### ISSUE THREAD

**Issue by roryokane** [Gozala/wisp#66]
When trying Wisp, I came upon a problem: since the function `(get …)` is taken, how do I call a global function `get` that is defined by other JavaScript? I wanted to call `get();`, but this does not work:

``` clojure
(get)
```

Eventually I realized that you could do this:

``` clojure
(.call get this)
```

then I wrote a macro for that:

``` clojure
(defmacro call-global [fun & args]
  `(.call ~fun ~@args))
```

Then I realized that there was a built-in macro for that, `call`. I hadn’t noticed it because the syntax highlighting in [Try Wisp](http://jeditoolkit.com/try-wisp/) didn’t highlight `call` in pink like it highlighted the other built-ins.

``` clojure
(call get)
```

However, `call` is not documented anywhere. It should be documented, and this method for escaping built-in functions specifically pointed out.

Maybe you’re saving the writing of detailed standard library documentation (an API reference) for later. If so, this Issue is to remind you to mention this use of `call` in its documentation, when you get to writing it.

**Comment by chr15m** [comment]
Seems like apply should be sufficient.
